name: DRC Files
on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'

  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      
  workflow_dispatch:

jobs:
  drc-files:
    name: DRC Everything
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
      
    steps:

    - name: Generate Short SHA Environment Variable
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: DRC PB_16v1 Files
      run: |
        cd PB_16v1
        rm -rf PB_16v1/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d PB_16v1

    - name: DRC PB_16v2_SMD Files
      run: |
        cd PB_16v2_SMD
        rm -rf PB_16v2_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d PB_16v2_SMD

    - name: DRC BBB_16 Files
      run: |
        cd BBB_16
        rm -rf BBB_16/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e BBB_16.kicad_sch -b BBB_16.kicad_pcb -d BBB_16

    - name: DRC BBB_16_SMD Files
      run: |
        cd BBB_16_SMD
        rm -rf BBB_16_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e BBB_16.kicad_sch -b BBB_16.kicad_pcb -d BBB_16_SMD

    - name: Upload Export Files as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output.zip
        path: |
          PB_16v1/PB_16v1/**
          PB_16v2_SMD/PB_16v2_SMD/**
          BBB_16/BBB_16/**
          BBB_16_SMD/BBB_16_SMD/**
        if-no-files-found: error
        retention-days: 60

